pipeline
{
  stages
  {
    stage("build")
    {
steps
      {
        echo "this is build stage"
      }
      stage("deploy")
      {
        steps
        {
          echo "this is deploy stage"
        }
        stage("test")
        {
          steps
          {
            echo " this is testing stage"
          }
        }
      }
      
